### ISSUE TITLE
Broken pip install

### ISSUE THREAD

**Issue by widlarizer** [ttsiodras/DataModellingTools#12]
The build as described in README.md does not lead to a functional install on either Windows or Linux, in exactly the same way. Using Python 3.8:
```
PS C:\Users\Emil\Documents\tools\DataModellingTools> pip3 install --user --upgrade .
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
```
Practically the same message on ubuntu 20.04 LTS with Python 3.9. When I rename setup.py.in to setup.py, I am able to install it, but run into [this issue](https://github.com/python/typed_ast/issues/126), which I solved by manually installing mypy. Still, I get this in install:
```
\site-packages\setuptools\dist.py:472: UserWarning: The version specified ('2.2-@SCM_REVISION@') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
```
So it's installing with a non-expanded version macro in the name. But that at least doesn't break the whole thing. Now when I run asn2datamodel on either linux or windows, I get this:
```
Traceback (most recent call last):
  File ".\asn2dataModel.py", line 27, in <module>
    from .commonPy import configMT, asnParser, cleanupNodes, verify
ImportError: attempted relative import with no known parent package
```
...is there something I'm missing? Is every usecase which isn't the pre-baked TASTE VM just considered deprecated?
Cheers, Emil @ esc Aerospace

**Comment by ttsiodras** [comment]
Hi, Emil. I just pushed bdf70668021dde56e638396ea799f6f1f7f8f7ff which fixes your issue.

DMT - as most other TASTE components - is mostly useful within the context of TASTE...  But we do offer solutions for people like you, who, for whatever reason choose to work outside the pre-made VM.  The instructions in https://taste.tools/ offer three different ways to install TASTE without using the VM:

- The  Docker-based installation, built from scratch (see https://gitrepos.estec.esa.int/taste/taste-setup/-/blob/master/Dockerfile ). 
- A chroot-ed installation, for non-Debian-based distros
- And a native install, if you are in a Debian-based one - though we recommend the first two options, to isolate your main distro.

These instructions build not just DMT, but many other TASTE dependencies: https://gitrepos.estec.esa.int/taste/taste-setup/-/tree/feature_buster/install - including distribution package dependencies, customization of your environment, etc.  Trying to reproduce everything these scripts do on your own is... not a wise course of action.

But if you do want to see what happens when the VM is built, it's all there for you to see - for example, in DMT's case, the README may be behind - as you noticed - but the relevant install script ( https://gitrepos.estec.esa.int/taste/taste-setup/-/blob/feature_buster/install/10_dmt.sh ) won't.

I hope this helps!
